name: app_laundry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2'

dependencies:
  flutter:
    sdk: flutter
  # --- INI ADALAH FORMAT YANG BENAR ---
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  intl: ^0.20.2
  http: ^1.5.0
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/
    - assets/sepatu.jpg
    - assets/Baju contoh.jpg
    - assets/baju-removebg-preview.png
    - assets/Timbangan-removebg-preview (1).png
    - assets/setrika.jpg
    - assets/timbang.jpg
    - assets/Karpet.jpg

    